/**
 * Regenerate Narration service — re-runs TTS for a compound clip that was
 * previously produced by the Spoiler Generator. Mirrors a subset of the
 * orchestrator pipeline:
 *
 *   1. Read `spoilerMetadata` from the target SubComposition.
 *   2. Run TTS batch over the stored narration text per segment with the
 *      user-selected voice / speed / language.
 *   3. Hand off to {@link applyNarrationRegen} which mutates the compound in
 *      place (durations follow the new narration; items shift accordingly).
 *
 * Notable: regen does NOT re-transcribe the new narration audio for
 * word-level subtitle timing. The original spoiler-generation pass already
 * produced a transcript; re-transcribing per regen would double the API
 * cost. Instead, subtitles in regen are rebuilt with the fallback path
 * (one TextItem per segment, full narration text, span-the-segment timing)
 * so the durations stay in sync with the new audio without extra calls.
 *
 * Failure of more than 50% of segments aborts the regen — same threshold as
 * the initial pipeline.
 */

import { createLogger } from '@/shared/logging/logger'

import {
  applyNarrationRegen,
  type NarrationRegenSegmentInput,
  type NarrationRegenResult,
} from './apply-narration-regen'
import { useCompositionsStore } from './deps/timeline'
import { mediaLibraryService } from './deps/media-library'
import { useProjectStore } from './deps/project'
import { runTtsBatch, summarizeBatch } from './tts-batch-runner'
import type { SpoilerSegment } from './types'

const logger = createLogger('SpoilerRegen')

class RegenAbortError extends DOMException {
  constructor() {
    super('Narration regeneration aborted by user.', 'AbortError')
  }
}

export type RegenStage = 'idle' | 'generating-narration' | 'applying' | 'done' | 'error'

export interface RegenProgress {
  stage: RegenStage
  message: string
  segmentIndex?: number
  segmentTotal?: number
  fraction?: number
}

export interface RegenerateNarrationInput {
  compositionId: string
  /** Voice id, or null to fall back to provider default. */
  voiceId: string | null
  /** Speed multiplier — typically 0.5..2.0. */
  speed: number
  /** Narration language ISO-639-1 — persisted on metadata for future regens. */
  language: string
}

export interface RegenerateNarrationOptions {
  onProgress: (progress: RegenProgress) => void
  signal?: AbortSignal
}

function checkAbort(signal: AbortSignal | undefined): void {
  if (signal?.aborted) throw new RegenAbortError()
}

function emit(options: RegenerateNarrationOptions, progress: RegenProgress): void {
  options.onProgress(progress)
}

export async function regenerateNarration(
  input: RegenerateNarrationInput,
  options: RegenerateNarrationOptions,
): Promise<NarrationRegenResult> {
  const projectId = useProjectStore.getState().currentProject?.id
  if (!projectId) {
    throw new Error('Open a project before regenerating narration.')
  }

  const composition = useCompositionsStore.getState().getComposition(input.compositionId)
  if (!composition) {
    throw new Error(`Compound clip ${input.compositionId} not found.`)
  }
  const metadata = composition.spoilerMetadata
  if (!metadata) {
    throw new Error(
      'This compound was not generated by the Spoiler Generator (no narration metadata).',
    )
  }
  if (metadata.segments.length === 0) {
    throw new Error('No narration segments found on this compound.')
  }

  // Build TTS-input segments from metadata. We reuse the SpoilerSegment shape
  // for compatibility with `runTtsBatch` even though several fields are
  // unused on the regen path.
  const segments: SpoilerSegment[] = metadata.segments.map((seg) => ({
    index: seg.index,
    narration: seg.narrationText,
    selectedClipRange: {
      startSec: seg.sourceClipRange.start,
      endSec: seg.sourceClipRange.end,
    },
    estimatedNarrationSec: 0,
  }))

  const total = segments.length
  emit(options, {
    stage: 'generating-narration',
    message: `Generating narration audio (0/${total})...`,
    segmentTotal: total,
    segmentIndex: 0,
  })
  checkAbort(options.signal)

  const ttsResults = await runTtsBatch({
    segments,
    projectId,
    speed: input.speed,
    // Regen always rebuilds via the cloud Custom AI endpoint — engine
    // selection lives on the dialog flow, not on stored compound metadata.
    engineConfig: { engine: 'custom', ...(input.voiceId ? { voice: input.voiceId } : {}) },
    maxConcurrency: 3,
    maxRetries: 2,
    ...(options.signal ? { signal: options.signal } : {}),
    onProgress: (current) => {
      emit(options, {
        stage: 'generating-narration',
        message: `Generating narration audio (${current}/${total})...`,
        segmentTotal: total,
        segmentIndex: current,
        fraction: total > 0 ? current / total : 0,
      })
    },
  })

  const summary = summarizeBatch(ttsResults)
  if (summary.failureRate > 0.5) {
    throw new Error(
      `TTS failed for ${summary.failed}/${summary.total} segments. ` +
        'Check the Custom AI Text-to-Speech configuration and try again.',
    )
  }

  // Resolve blob URLs for the new narration audio so the timeline can play.
  const regenSegments: NarrationRegenSegmentInput[] = []
  for (const result of ttsResults) {
    if (!('mediaId' in result) || !result.mediaId) {
      // TTS failed for this segment — skip; apply step keeps the original.
      continue
    }
    try {
      const blobUrl = await mediaLibraryService.getMediaBlobUrl(result.mediaId)
      if (!blobUrl) {
        logger.warn(`No blob URL for regenerated narration ${result.mediaId}`)
        continue
      }
      regenSegments.push({
        index: result.index,
        mediaId: result.mediaId,
        blobUrl,
        durationSec: result.durationSec,
      })
    } catch (err) {
      logger.warn(`Failed to resolve blob URL for ${result.mediaId}`, err)
    }
  }

  if (regenSegments.length === 0) {
    throw new Error('No narration audio could be regenerated. Aborting before mutation.')
  }

  emit(options, { stage: 'applying', message: 'Applying changes to the compound...' })
  checkAbort(options.signal)

  const result = applyNarrationRegen({
    compositionId: input.compositionId,
    regenSegments,
    voiceId: input.voiceId,
    speed: input.speed,
    language: input.language,
  })

  emit(options, {
    stage: 'done',
    message: 'Narration regenerated successfully.',
  })

  return result
}
